### ISSUE TITLE
Doesn't work when multiple requests are sent at the same time

### ISSUE THREAD

**Issue by anghelalexandra** [pasindud/npm-wappalyzer#1]
Hi there,

I've noticed that if I sent multiple requests at the same time, the url from the wappalyzer object is overwritten and basically it retrieves the apps from the last requested url. This doesn't work well with the async requests from Node.js, is there a way to fix it?

**Comment by pasindud** [comment]
Thanks, got that fixed now check it out now :+1:

**Comment by anghelalexandra** [comment]
It works now, thanks a lot for the quick reply. :)
