### ISSUE TITLE
Browser Extension Wappalyzer

### ISSUE THREAD

**Issue by aghazal** [pasindud/npm-wappalyzer#2]
Is this package supposed to give the same results as the browser extension wappalyzer (https://wappalyzer.com/) ?

For every website that I tested with, the browser extension showed more technologies than this package.

**Comment by pasindud** [comment]
The apps.json file gets outdated, fixed it with a post install script should be good now

**Comment by aghazal** [comment]
Thanks for the quick response.
I have updated the package but still the browser extension shows more technologies than the package.
